image: Visual Studio 2017
configuration: Release
cache: c:\tools\vcpkg\installed\
build_script:
- ps: >-
    cd C:/tools/vcpkg

    git pull

    bootstrap-vcpkg.bat

    vcpkg install sfml:x86-windows --head

    cd C:/projects/sfml-doom

    cmake . -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake

    cmake --build . --target package

artifacts:
  - path: '*.exe'
    name: Installer
deploy:
  provider: GitHub
  auth_token:
    secure: Uh9bW+VtZC5N7CVz5UpuxZvPJ58SpbsXBvEz6Q4vQhLcjZEFzYMhH+bS9VAPV+S8
  artifact: Installer
  prerelease: true
  force_update: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only