name: Build for Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: lukka/run-vcpkg@v11

    - uses: ConorMacBride/install-package@v1
      with:
        apt: libx11-dev libxi-dev libxrandr-dev libxcursor-dev libxi-dev libudev-dev libgl1-mesa-dev

    - name: Configure
      run: cmake --preset default -G"Ninja Multi-Config"

    - name: Build Debug
      run: cmake --build --preset default --config Debug

    - name: Build Release
      run: cmake --build --preset default --config Release

    - name: Package Release
      run: cpack --preset default

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sfml-doom
        path: out/package/default/*.zip