name: Build for Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v4
    - uses: lukka/run-vcpkg@v11
    
    - name: Configure
      run: cmake --preset default

    - name: Build Debug
      run: cmake --build --preset default --config Debug

    - name: Build Release
      run: cmake --build --preset default --config Release

    - name: Package Release
      run: cpack --preset default
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sfml-doom
        path: out/package/default/*.zip

